config/routes.rb
Rails.application.routes.draw do

  root :to => "games#index"

  resources :games

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	attr_accessible :title, :description, :image, :swf

	mount_uploader :image, ImageUploader
	mount_uploader :swf, SwfUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
		@games = Game.all
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(params[:game])
		if @game.save
			flash[:notice] = "Successfully Added Game"
			redirect_to @game
			else
			render :action => 'new'
		end
	end


	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])
		if @game.update_attributes(params[:game])
			flash[:notice] = "Successfully updated Game"
			redirect_to @game
			else
				render :action => 'edit'
		end
	end

	def show
		@game = Game.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
	def title(page_title, show_title = true)
      content_for(:title) { h(page_title.to_s) }
      @show_title = show_title
    end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/games/_form.html.erb
<div class="panel"><br>
	<div class="container panel-body">
		<%= form_for @game,:html => {:multipart => true} do |f| %>
			
			<div>
				<p>
					<%= f.label :title, "Title : " %>
					<%= f.text_field :title %>
			    </p>
			</div>
			<div>
				<p>
					<%= f.label :image, "Upload Image :" %>
					<%= f.file_field :image %>
			    </p>
			</div>
			<div>
				<p>
					<%= f.label :swf, "Upload SWF File" %>
					<%= f.file_field :swf %>
			    </p>
			</div>
			<div>
				<p>
					<%= f.label :description, "Description : " %>
					<%= f.text_area :description %>
			    </p>
			</div>

			<div>
				<p>
				    <%= f.submit %>
			    </p>
			</div>


		<% end %>
</div>
</div>

app/views/games/edit.html.erb
<h1>Edit Game</h1>
<%= render 'form' %>
<%= link_to "Back to Game List", games_path %>

app/views/games/index.html.erb
<section class="container">

<h1>Flash Game List</h1>
<div class="container">
	<div class="thumbnails">
	<div class="row visable-sm visable-lg">
		<% @games.each do |game| %>
			<div class="col-xs-1 col-md-3">
				 <div class="img-thumbnail">
					<div><a href="<%= game_path(game) %>"><%= image_tag game.image_url(:thumb).to_s %></a>
				        <div><%= game.title %></div>
					    <div class="action"><%= link_to "edit", edit_game_path(game) %></div>
					</div>
				 </div>
			</div>
		<% end %>
	</div>
	</div>
</div>
</section>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to "Back to Game List", games_path %>

app/views/games/show.html.erb
<form>	
  <section>
    <div class="container">
      <div class="panel panel-sucess">
          <div class="columns">
              <div class="col1">
                  <div class="thumbnail col-md-6 col-lg-11">
                     <div><h3><%= @game.title %></h3></h3></div>
                     <div>
                        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="500" height="430" id="<%= @game.title %>" align="middle">
                               <param name="allowScriptAccess" value="sameDomain" />
                               <param name="movie" value="<%= @game.swf_url %>" />
                               <param name="quality" value="high" />
                               <param name="scale" value="noscale" />
                               <param name="bgcolor" value="#ffffff" />
                               <embed src="<%= @game.swf_url %>" quality="high" scale="noscale" bgcolor="#ffffff" width="500" height="430" name="<%= @game.title %>" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
                       </object>
                      </div>
                  </div>
              </div>
              <div class="col2">
                      <br>
                      <br>
                      <br>
                      <br>
                      <div><h4>Titile :  <%= @game.title %></h4></div>
                      <div><h4>Game Description : <%= @game.description %></h4></div>
                      <div class="raty"><h5>Ratting : </h5></div>
              </div>
          </div>
      </div>
  	</div>
 </section>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashgame</title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  <link  href="stylesheets/bootstrap.min.css" rel="stylesheets" >
  <link  href="stylesheets/amelia_bootstrap.min.css" rel="stylesheets" >
  <link  href="stylesheets/site.css" rel="stylesheets">
  <%= yield (:head) %>
</head>
<body>
	<div id="page" class="container">
	<header>
		<div class="container">
			<div id="menu" class="navbar navbar-default">
				<div class="navbar-header">
					<button class="btn btn-success navbar-toggle">
					<span class="glyphicon glyphicon-chevron-down">
					</span></button>
					<div id="logo">
					<a href="."><h2>Flash Games</h2></a>
				</div>
				</div>
				<div class="navbar-collapse collapse">
				  <ul class="nav navbar-nav navbar-right">
						
						<li><%= active_link_to "Games", games_path %></li>
						<li><%= active_link_to "Uploade Games", new_game_path %></li>
						
				  </ul>
				</div>
			</div>
		</div>

	</header>
<div id="container">
	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	<%= content_tag :h1, yield(:title) if show_title? %>
<%= yield %>
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</body>
</html>